// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Character documents
 */
interface CharacterDocumentData {
  /**
   * Slug field in *Character*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: character.slug
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  slug: prismic.KeyTextField;

  /**
   * Image Character field in *Character*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: character.image_character
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_character: prismic.ImageField<never>;

  /**
   * Name Character field in *Character*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: character.name_character
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name_character: prismic.KeyTextField;

  /**
   * Description Character field in *Character*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: character.description_character
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description_character: prismic.RichTextField;
}

/**
 * Character document from Prismic
 *
 * - **API ID**: `character`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CharacterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CharacterDocumentData>,
    "character",
    Lang
  >;

/**
 * Content for HOME documents
 */
interface HomeDocumentData {
  /**
   * Subtitle Hero field in *HOME*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.subtitle_hero
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle_hero: prismic.KeyTextField;

  /**
   * Title Hero field in *HOME*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.title_hero
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_hero: prismic.KeyTextField;

  /**
   * Description Hero field in *HOME*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.description_hero
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description_hero: prismic.RichTextField;

  /**
   * Label Button field in *HOME*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.label_button
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label_button: prismic.KeyTextField;

  /**
   * Url Button field in *HOME*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.url_button
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url_button: prismic.LinkField;

  /**
   * Label Trailer field in *HOME*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.label_trailer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label_trailer: prismic.KeyTextField;

  /**
   * thumb trailer field in *HOME*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.thumb_trailer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  thumb_trailer: prismic.ImageField<never>;
}

/**
 * HOME document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HomeDocumentData>, "home", Lang>;

export type AllDocumentTypes = CharacterDocument | HomeDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      CharacterDocument,
      CharacterDocumentData,
      HomeDocument,
      HomeDocumentData,
      AllDocumentTypes,
    };
  }
}
